name: Welcome Script

on: [push]

jobs:
  welcome-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show welcome message
        run: echo "í±‹ Welcome to this GitHub Action workflow!"

